name: simple_flutter_app
description: A simple Flutter app for OSU Assignment 5 showcasing navigation, theme switching, and UI layout.
publish_to: 'none' # This is a private project; not intended for publishing.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


